spring:
  datasource:
    url: jdbc:postgresql://bankweb-app.c72yiso6ixci.ap-south-1.rds.amazonaws.com:5432/bankweb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
